server:
  port: 9000 # 服务端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 服务注册中心地址

spring:
  application:
    name: provider-service # 服务名称
  resources: # 指定静态资源的路径
    static-locations: classpath:/

  cloud:
    config:
#      discovery:
#        enabled: true
#        service-id: configServer
      uri: http://localhost:8888/
      profile: dev #环境
      label: 0.1 #版本

# 为了能够刷新配置
management:
  security:
    enabled: false