server:
  port: 9003
spring:
  application:
    name: sidecarTest

sidecar:
  port: 9004
  health-uri: http://localhost:9004/health.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#eureka:
#  instance:
#    app-group-name: mysidecargroup
#  client:
#    serviceUrl:
#      defaultZone: http://user:password@localhost:8761/eureka/

ribbon:
  ServerListRefreshInterval: 5000
  ReadTimeout: 7777

endpoints:
  refresh:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

